language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
install:
  - bash -ex libs/travis-conda-scripts/scripts/travis_install.sh
before_script:
  # this is for running test coverage on travis
  - pip install numpy matplotlib scipy astropy pandas
  - pip install quantities neo elephant
  - pip install pytest coverage codecov
  - python setup.py install
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - coverage run --source exana -m py.test -s --doctest-modules --ignore setup.py
  - coverage report
  - source libs/travis-conda-scripts/scripts/config.sh
  - bash -ex libs/travis-conda-scripts/scripts/build.sh
after_success:
  - codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex libs/travis-conda-scripts/scripts/upload.sh cinpla main
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash -ex libs/travis-conda-scripts/scripts/upload.sh cinpla dev
    on:
      branch: dev
