package:
  name: exana
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}

source:
  path: .
 
build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - gitpython

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - gitpython

test:
  imports:
    - exana

about:
  home: https://github.com/CINPLA/exana/
  license: GPLv3
  license_file: LICENSE
