package:
    name: exana
    version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}
source:
    git_url: ..
build:
    noarch: python
    script: pip install neo elephant && python setup.py install
requirements:
    build:
        - python
        - setuptools
        - pip
        - numpy
        - pandas
        - matplotlib
        - scipy
        - astropy
        - quantities
    run:
        - python
        - setuptools
        - pip
        - numpy
        - astropy
        - pandas
        - scipy
        - quantities
test:
  imports:
    - exana
  commands:
    - python -c "import exana"
    - coverage run --source tests -m py.test -s
    - coverage report
    - codecov
    - cd docs ; make doctest
about:
    description: ''
    dev_url: https://github.com/CINPLA/exana
    license: GNU GPLv3
    license_family: GPL
    license_file: LICENSE
extra:
    recipe-maintainers:
        - dragly
